#PBS -N mark_<sample>
#PBS -l nodes=1:ppn=4
#PBS -l walltime=10:00:00
#PBS -S /bin/bash
#PBS -q xxxxxxx
#PBS -j oe

source activate wes
gatk --java-options "-Xmx20G -Djava.io.tmpdir=/path/to/tmp"  MarkDuplicates \
        I=/path/<sample>.sort.bam \
        O=/path/<sample>.rmdup.bam \
        VALIDATION_STRINGENCY=LENIENT \
        MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 \
        M=/path/<sample>.sort.addhead.rmdup.metric

