#PBS -N <sample>
#PBS -l nodes=1:ppn=4
#PBS -l walltime=01:00:00
#PBS -S /bin/bash
#PBS -q normal_3
#PBS -j oe

source activate wes
java -jar /public/home/liuxs/anaconda3/envs/wes/share/picard-2.18.23-0/picard.jar ReorderSam\
 REFERENCE=/public/home/liuxs/biodata/reference/genome/hg19/hg19.fa\
 INPUT=/public/home/liuxs/ncbi/dbGaP-22002/bwa/sam/<sample>.sam\
 OUTPUT=/public/home/liuxs/ncbi/dbGaP-22002/bwa/reorder_sam/<sample>.reorder.sam

