#PBS -N mem_<sample>
#PBS -l nodes=1:ppn=4
#PBS -l walltime=20:00:00
#PBS -l mem=20gb
#PBS -S /bin/bash
#PBS -q normal_3
#PBS -j oe

source activate wes
workdir=/public/home/liuxs/ncbi/dbGaP-22002/bwa/sam
cd $workdir
bwa mem -M -R "@RG\tID:<sample>\t\
LM:<sample>\t\
SM:<sample>\t\
PL:illumina\tPU:<sample>"\
 /public/home/liuxs/biodata/reference/genome/hg19/hg19.fa /public/home/liuxs/ncbi/dbGaP-22002/fastq_clean/<sample>_1_val_1.fq.gz\
 /public/home/liuxs/ncbi/dbGaP-22002/fastq_clean/<sample>_2_val_2.fq.gz\
> <sample>.sam                    
